<a href="https://colab.research.google.com/github/Yasaswini223/ML-23AG1A66E3/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import numpy as np

In [30]:
list=[2,3,5,7]
array1 = np.array(list)
print(array1)

[2 3 5 7]


In [31]:
array1 = np.array([2,3,5,7])
print(array1)

[2 3 5 7]


In [32]:
array1 = np.array([[1,3,5,7],
                   [2,3,6,8]])
print(array1)

[[1 3 5 7]
 [2 3 6 8]]


In [33]:
array1 = np.array([[[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]],

                 [[13,14,15,16],
                  [17,18,19,20],
                  [21,22,23,24]]])
print(array1)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [34]:
array1 = np.array([1,3,5])
print(array1.dtype)

int64


In [35]:
print(array1.ndim)

1


In [36]:
print(array1.size)

3


In [37]:
array1 = np.array([[1,2,3],
                   [6,7,8]])
print(array1.shape)

(2, 3)


In [38]:
array1 = np.array([6,7,8,9,10])
array2 = np.array([2,3,4,5,6])
print(array1.itemsize)
print(array2.itemsize)

8
8


In [39]:
array1 = np.array([2,3,4])
print("Data of array1 is: ",array1.data)

Data of array1 is:  <memory at 0x7c55ae0dfac0>


In [41]:
array1 = np.array([1,4,6,8,9,12])
print(array1[0])
print(array1[4])
print(array1[5])

1
9
12


In [42]:
array1[4]=10
print(array1)

[ 1  4  6  8 10 12]


In [43]:
array1 = np.array([[1, 3, 5, 7],
                       [9, 11, 13, 15],
                       [2, 4, 6, 8]])
element1 = array1[1, 3]
print("4th Element at 2nd Row:",element1)
element2 = array1[0, 1]
print("2nd Element at First Row:",element2)

4th Element at 2nd Row: 15
2nd Element at First Row: 3


In [44]:
array1 = np.array([1, 2, 3, 4, 5])
median = np.median(array1)
print(median)


3.0


In [45]:
marks = np.array([76, 78, 81, 66, 85])
mean_marks = np.mean(marks)
print(mean_marks)

77.2


In [46]:
marks = np.array([76, 78, 81, 66, 85])
std_marks = np.std(marks)
print(std_marks)


6.368673331236263


In [47]:
marks = np.array([76, 78, 81, 66, 85])
std_marks = np.min(marks)
print(std_marks)


66


In [48]:
marks = np.array([76, 78, 81, 66, 85])
std_marks = np.max(marks)
print(std_marks)

85
